### ISSUE TITLE
L4L7 - PBR one-arm with two devices (HA) and same interfaces

### ISSUE THREAD

**Issue by ccoueffe** [netascode/terraform-aci-l4l7-device#18]
### Terraform 

- v1.3.6

- registry.terraform.io/netascode/l4l7-device/aci 0.2.3 for tenant.aci_l4l7_device...

### Affected Resource

- tenant.aci_l4l7_device

### Terraform configuration

Context:
L4L7 devices with an ASA cluster in Active/Passive in one-arm. Interface named Gi1-2910 is used for consumer and provider with same encap.

<img width="831" alt="Screenshot 2023-03-16 at 13 39 30" src="https://user-images.githubusercontent.com/75327499/225619784-8da4bb39-aaac-4fed-941c-a9f1abf39d1a.png">

Data source:
```yaml
services:
        l4l7_devices:
          - name: ASA5506_PBR
            type: PHYSICAL
            service_type: FW
            context_aware: single-Context
            managed: false
            physical_domain: Services_PHY
            function: 'GoTo'
            concrete_devices:
              - name: ASA1
                interfaces:
                  - name: Gi1-2910
                    pod_id: 1
                    node_id: 198
                    module: 1
                    port: 48
              - name: ASA2
                interfaces:
                  - name: Gi1-2910
                    pod_id: 1
                    node_id: 199
                    module: 1
                    port: 48
            logical_interfaces:
              - name: Consumer
                vlan: 2910
                concrete_interfaces:
                  - device: ASA1
                    interface_name: Gi1-2910
                  - device: ASA2
                    interface_name: Gi1-2910
              - name: Provider
                vlan: 2910
                concrete_interfaces:
                  - device: ASA1
                    interface_name: Gi1-2910
                  - device: ASA2
                    interface_name: Gi1-2910 
```

### Error log

```bash
│ Error: Duplicate object key
│ 
│   on .terraform/modules/tenant.aci_l4l7_device/main.tf line 127, in resource "aci_rest_managed" "vnsRsCIfAttN":
│  127:   for_each   = { for concrete_iface in local.logical_iface_concrete_iface : concrete_iface.id => concrete_iface }
│     ├────────────────
│     │ concrete_iface.id is "Consumer-Gi1-2910"
│ 
│ Two different items produced the key "Consumer-Gi1-2910" in this 'for'
│ expression. If duplicates are expected, use the ellipsis (...) after the
│ value expression to enable grouping by key. 
```

Keys:

```bash
> terraform state list | grep module.aci_l4l7_device
module.tenant["ccoueffe-tn"].module.aci_l4l7_device["ASA5506_PBR"].aci_rest_managed.vnsCDev["ASA1"]
module.tenant["ccoueffe-tn"].module.aci_l4l7_device["ASA5506_PBR"].aci_rest_managed.vnsCDev["ASA2"]
module.tenant["ccoueffe-tn"].module.aci_l4l7_device["ASA5506_PBR"].aci_rest_managed.vnsCIf["ASA1-Gi1-2910"]
module.tenant["ccoueffe-tn"].module.aci_l4l7_device["ASA5506_PBR"].aci_rest_managed.vnsCIf["ASA2-Gi1-2910"]
module.tenant["ccoueffe-tn"].module.aci_l4l7_device["ASA5506_PBR"].aci_rest_managed.vnsLDevVip
module.tenant["ccoueffe-tn"].module.aci_l4l7_device["ASA5506_PBR"].aci_rest_managed.vnsLIf["Consumer"]
module.tenant["ccoueffe-tn"].module.aci_l4l7_device["ASA5506_PBR"].aci_rest_managed.vnsLIf["Provider"]
module.tenant["ccoueffe-tn"].module.aci_l4l7_device["ASA5506_PBR"].aci_rest_managed.vnsRsALDevToPhysDomP[0]
module.tenant["ccoueffe-tn"].module.aci_l4l7_device["ASA5506_PBR"].aci_rest_managed.vnsRsCIfAttN["Consumer-Gi1-2910"]
module.tenant["ccoueffe-tn"].module.aci_l4l7_device["ASA5506_PBR"].aci_rest_managed.vnsRsCIfAttN["Provider-Gi1-2910"]
module.tenant["ccoueffe-tn"].module.aci_l4l7_device["ASA5506_PBR"].aci_rest_managed.vnsRsCIfPathAtt_port["ASA1-Gi1-2910"]
module.tenant["ccoueffe-tn"].module.aci_l4l7_device["ASA5506_PBR"].aci_rest_managed.vnsRsCIfPathAtt_port["ASA2-Gi1-2910"]
```

### Enhancement
Need to create id with at least device and interface.
```tf
  logical_iface_concrete_iface = flatten([
    for logical_iface in var.logical_interfaces : [
      for concrete_iface in lookup(logical_iface, "concrete_interfaces", []) : {
        id             = "${logical_iface.name}-${concrete_iface.interface}".       <<<
        logical_iface  = logical_iface.name
        concrete_iface = concrete_iface.interface
        device         = concrete_iface.device
      }
    ]
  ])
} 
```
